### ISSUE TITLE
Dodatkowe wykresy

### ISSUE THREAD

**Issue by radluki** [radluki/Napedy_Elektryczne#1]
Potrzebujemy dodatkowych wykresów. Informacje jakich są na wiki. Proszę abyście je wygenerowali i umieścili w jakimś nowym folderze. Aktualna wersja sprawozdania znajduje się w tex_maszyny.

**Comment by radluki** [comment]
Aby zobaczyć tabelkę w czytelnej formie naciśnijcie edit na stronie wiki.

**Comment by radluki** [comment]
Napiszcie, czy otrzymaliście informację i czy jest to dobry sposób komunikowania się.

**Comment by Meriadock** [comment]
Po coś są te wszystkie opcje w GitHubie - zadania, wiki itp. Ja tam jednak nie loguję się prawie nigdy przez stronkę, więc nie jest to jakaś rewelacja dla mnie. Dla mnie obojętne, można też dane i inne informacje przez maila normalnie wysyłać.

**Comment by Meriadock** [comment]
A co to jest to P''? Chodzi o P2, czy o co?

W dniu 20 marca 2015 15:33 użytkownik radluki notifications@github.com
napisał:

**Comment by radluki** [comment]
Nie mam pomysłu co to może być. Skorzystaj z naszych danych pomiarowych, a obroty dopasuj może na podstawie prądu.Czyli P i P1 z wiki raczej nie bierz pod uwagę.

**Comment by radluki** [comment]
Co do wysyłania danych na maila, to chyba github to robi. Oczywiście można pewnie wyłączyć powiadomienia. Jeśli nie dostałeś powiadomienia na maila z githuba to albo jest w spamie, albo masz wyłączoną tę opcję.

**Comment by Meriadock** [comment]
Dostałem, też na maila, bo tak to bym się o tym dowiedział najwcześniej za
parę miesięcy ;P

W dniu 20 marca 2015 17:21 użytkownik radluki notifications@github.com
napisał:

**Comment by radluki** [comment]
Przeanalizowałem te dane, narysowałem wykresy.
Sprawdźcie tylko czy się nie pomyliłem. 
Aktualna wersja sprawozdania: A3_aktualne.pdf
