### ISSUE TITLE
Sprawko - zadania

### ISSUE THREAD

**Issue by radluki** [radluki/Napedy_Elektryczne#14]
Do zrobienia:
1) Weryfikacja wykonanych wykresów: 
          - T=f(n)
          - sprawność = g(moc oddana silnika)
2) Co to jest regulator tyrystorowy, jak działa i czego się spodziewać na wykresach.
3) Interpretacja wykresów, w tym punkcie należy uzasadnić dlaczego otrzymaliśmy takie wyniki, albo wykazać że są błędne. Jeżeli wyniki będą błędne to szukajcie błędu w:
https://github.com/radluki/Napedy_Elektryczne/blob/master/ea3/sprawko%20elektro.xlsx

Wykonałem jakieś obliczenia. Wydaje mi się, że sprawność którą dostaliśmy w pliku jest źle policzona, poprawiłem to i wykreśliłem wykresy.

W komentarzach wpisujcie za co się zabieracie, ewentualnie czy zamierzacie coś zrobić, jeśli nie to też napiszcie, żeby było wiadomo.

Na zachętę dodam że za nieoddanie sprawozdania możemy być zmuszenie do powtarzania ćwiczenia.

**Comment by macpod1994** [comment]
Biorę się za 2) czyli regulator tyrystorowy
