### ISSUE TITLE
Zagadnienie z oporem pojemnosciowym

### ISSUE THREAD

**Issue by radluki** [radluki/Napedy_Elektryczne#4]
Dlaczego gdy dajemy opor pojemnosciowy to charakterystyka idzie w gore? Poszukaj jakiegoś wytlumaczenia w necie. Jak cos znajdziesz to napisz rozwiazanie, albo umiesc w repozytorium linki do zrodla.

**Comment by radluki** [comment]
Zadeklaruj się do kiedy mam się spodziewać rozwiazania.

**Comment by legoxx** [comment]
Do 22:00 powinienem się wyrobić.

W dniu 23 marca 2015 18:14 użytkownik radluki notifications@github.com
napisał:

**Comment by macpod1994** [comment]
Biorę się za wnioski

W dniu 23 marca 2015 19:29 użytkownik legoxx notifications@github.com
napisał:

**Comment by legoxx** [comment]
http://www.ely.pg.gda.pl/e-mechatronika/dydaktyka/mele/wyklad/2011_2012/Skrypt%20ME%20wokol%20nas_str_tyt_rozdz_6.pdf
- 20 strona
  http://bezel.com.pl/index.php/maszyny-elektryczne/maszyny-synchroniczne
  Na tych stronach znalazłem wzory opisujące wartość U(I) wykorzystujące
  reaktancje, uwzględniając reaktancje kondensatora napięcie powinno
  wzrastać. W książce Plamitzer'a od str 461 też coś o tym jest ale ja nie
  mam głowy do tej ksiazki

W dniu 23 marca 2015 19:29 użytkownik Dawid Legutki dawidlegutki@gmail.com
napisał:

**Comment by macpod1994** [comment]
zrobiłem commita ze swoim wytłumaczeniem. Jest ono autorskie, dlatego sprawdźcie to proszę.

**Comment by radluki** [comment]
Chyba zapomniałeś o pushowaniu. Nie mamy dostępu do twoich poprawek.

**Comment by radluki** [comment]
Rys. 7 z drugiego źródła zaproponowanego przez Dawida dużo tłumaczy. Można by go umieścić w sprawozdaniu.

**Comment by radluki** [comment]
Zgadza się tak to chyba działa. Sprawdź czy to co napisałem w sprawozdaniu ci odpowiada.
