### ISSUE TITLE
Rozruchowa

### ISSUE THREAD

**Issue by radluki** [radluki/Napedy_Elektryczne#8]
Uzupełnij Opis/wnioski_rozruchowa.txt odnoszące się do Wykresy/Rozruchowa.png

**Comment by macpod1994** [comment]
Dodałem wnioski

**Comment by radluki** [comment]
Skompilowałem, mam jedną uwagę. Koduj w UTF-8(bez BOM), da się to ustawić w notepad++ zakładka format. Inaczej kompilator wyrzuca mi błędy. Możesz sprawdzić jakie zmiany wprowadziłem do waszych plików.
